services:
  nginx:
    image: nginx:alpine
    container_name: portfolio_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./portfolio-laravel:/var/www/laravel
      - ./portfolio-next/out:/var/www/next # serve buildani Next.js
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./Docker/nginx/certs:/etc/nginx/certs # ovde certifikati
    depends_on:
      - php
      - mysql
    networks:
      - portfolio_network

  php:
    build:
      context: ./Docker/php8.3
      dockerfile: Dockerfile
    container_name: portfolio_php
    volumes:
      - ./portfolio-laravel:/var/www/laravel
      - ./Docker/php8.3/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - portfolio_network

  mysql:
    image: mysql:8.0
    container_name: portfolio_mysql
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Sarajevo
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Docker/mysql/my.cnf:/etc/mysql/my.cnf
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - portfolio_network

  nextjs:
    build:
      context: ./portfolio-next
      dockerfile: Dockerfile
    container_name: portfolio_nextjs
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://mirzaredzic.hopto.org/api
    volumes:
      - ./portfolio-next:/app
      - ./portfolio-next/out:/app/out  # Osigurava da out direktorij perzistira
    networks:
      - portfolio_network
    command: sh -c "npm ci && npm run build && npm run export && echo 'Next.js build completed' && tail -f /dev/null"

networks:
  portfolio_network:
    driver: bridge

volumes:
  mysql_data: