version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - portfolio-network

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      DEFAULT_EMAIL: tvoj@email.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - portfolio-network

  php:
    ...
    environment:
      - VIRTUAL_HOST=mirzaredzic.hopto.org
      - LETSENCRYPT_HOST=mirzaredzic.hopto.org
      - LETSENCRYPT_EMAIL=tvoj@email.com

  nginx:
    image: nginx:1.21
    container_name: portfolio-nginx
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./portfolio-laravel:/var/www/laravel
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - portfolio-network
    environment:
      - VIRTUAL_HOST=mirzaredzic.hopto.org
      - LETSENCRYPT_HOST=mirzaredzic.hopto.org
      - LETSENCRYPT_EMAIL=tvoj@email.com

  nextjs:
    ...
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=mirzaredzic.hopto.org
      - LETSENCRYPT_HOST=mirzaredzic.hopto.org
      - LETSENCRYPT_EMAIL=tvoj@email.com

networks:
  portfolio-network:
    driver: bridge

volumes:
  mysql-data:
