version: '3'

services:
  php:
    build:
      context: ./portfolio-laravel
      dockerfile: Dockerfile
    container_name: portfolio-php
    restart: unless-stopped
    working_dir: /var/www/laravel
    volumes:
      - ./portfolio-laravel:/var/www/laravel
    networks:
      - portfolio-network
    depends_on:
      - mysql

  nginx:
    image: nginx:1.21
    container_name: portfolio-nginx
    restart: unless-stopped
    ports:
      - "8443:80"
    volumes:
      - ./portfolio-laravel:/var/www/laravel
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - portfolio-network
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: portfolio-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - portfolio-network
      
  nextjs:
    build:
      context: ./portfolio-next
      dockerfile: Dockerfile.next
    container_name: portfolio-nextjs
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - portfolio-network
    environment:
      - NEXT_PUBLIC_API_URL=http://34.76.223.210:8443/api
      - NEXT_PUBLIC_API_TOKEN=6|U7fyXkbpHn01uQMbuVVhKOj9RsCLlaqTKivcRnwg2f4cdadb

networks:
  portfolio-network:
    driver: bridge

volumes:
  mysql-data: