services:
  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./portfolio-laravel:/var/www/laravel
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - php
      - nextjs
    networks:
      - portfolio-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: portfolio-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - portfolio-network
    command: certonly --webroot --webroot-path=/var/www/certbot --email mirzaredzic9@gmail.com --agree-tos --no-eff-email -d mirzaredzic.duckdns.org --force-renewal --non-interactive
    depends_on:
      - nginx

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-php
    volumes:
      - ./portfolio-laravel:/var/www/laravel
    networks:
      - portfolio-network
    restart: unless-stopped

  nextjs:
    build:
      context: ./portfolio-next
      dockerfile: Dockerfile
    container_name: portfolio-nextjs
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://mirzaredzic.duckdns.org/api
    networks:
      - portfolio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3

  mysql:
    image: mysql:8.0
    container_name: portfolio-mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - portfolio-network
    restart: unless-stopped

networks:
  portfolio-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local