services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./portfolio-laravel:/var/www/laravel
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - php
      - nextjs
    networks:
      - portfolio-network
    restart: always

  php:
    build:
      context: ./portfolio-laravel
      dockerfile: Dockerfile
    volumes:
      - ./portfolio-laravel:/var/www/laravel
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=mysql
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_URL=http://mirzaredzic.duckdns.org
    networks:
      - portfolio-network
    restart: always

  nextjs:
    build:
      context: ./portfolio-next
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://mirzaredzic.duckdns.org
    networks:
      - portfolio-network
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - portfolio-network
    restart: always

networks:
  portfolio-network:
    driver: bridge

volumes:
  mysql_data: